#!/usr/bin/perl
#
##########################################################################
#
# calcTimes4
#
# Author:       Fabian Herschel, August 2021
# Support:      linux@sap.com
# License:      GNU General Public License 2 (GPLv2)
# Copyright (c) 2021 SUSE LLC.
#
##########################################################################
#
use strict;

# searching for SAPHanaController reported runimes

my $runTime;
my $timeStamp;

# SAPHanaController.*action.*monitor.*rc
#2021-07-30T21:08:51.982604+00:00 p1ldassps4006 SAPHanaController(rsc_SAPHanaCon_PEW_HDB20)[180953]: INFO: RA ==== end action monitor_clone with rc=0 (0.180.0.0614.1735) (1s)====

while (<>) {
  chomp();
  if (/.*T([0-9]+:[0-9]+:[0-9]+).* SAPHanaController.*INFO: RA.*action monitor_clone with rc=.*\(([0-9]+)s\)===/) {
    $timeStamp = $1;
    $runTime = $2;
    if ( $runTime > 0 ) {
      printf("%s %s\n", $timeStamp, $runTime);
    }
  }
}
