#!/usr/bin/perl
#
# SAPHanaSR-show-hadr-runtimes
#
# Description:  
#              Analyses SAP HANA nameserver trace files and calculates HA/DR hook script run times.
#              Only for specific known SUSE HA/DR providers.
#              Work in progress.
#
##############################################################################
#
# SAPHanaSR-show-hadr-runtimes
# Author:       Fabian Herschel, Lars Pinne, August 2021
# Support:      feedback@suse.com
# License:      GNU General Public License (GPL) V2
#               (c) 2021 SUSE LLC
#
# An example usage:
#      See usage() function below for more details...

use strict;

# use as filter (for first)
# nameserver_suse11.31001.002.trc:
# [7138]{-1}[-1/-1] 2021-08-19 15:44:50.974343 i ha_dr_slow       slow.py(00049) : slow.srConnectionChanged() method end with rc=0
# 
# [<ID>]<dont-know-what-that-is> <date> <time> <level> <who> <where> <message>
# <ID>: Number ([0-9]+)
# <dont-know-what-that-is>: Skip till whitespace
# <date>: Day YYYY-MM-DD ([0-9]+-[0-9]+-[0-9]+)
# <time>: Time HH:MM:SS.mmmmmm ([0-9]+:[0-9]+:[0-9]+\.[0-9]+)
# <level>: i (w, e ) ?
# <what>: string-till-whitespace
# <where>: string-till-whitespace
# colon
# <message>: string-till-end
#

my $idPat = "[0-9]+";
my $dnkwti = "[^ ]+";

my $day = "[0-9]+";
my $month = "[0-9]+";
my $year = "[0-9]+";
my $date = "$day-$month-$year";

my $hour = "[0-9]+";
my $minute = "[0-9]+";
my $second = "[0-9]+";
my $msecond = "[0-9]+";
my $time = "$hour:$minute:$second\.$msecond";

my $level = "[a-z]";
my $what = "[^ ]+";
my $where = "[^ ]+";
my $message = ".*";
my $WS = " +";
my %countId;
my %doubles;
my %times;
my %runtimes;

#sub testDoubles
#{
#	if ( ( $fWhat =~ /ha_dr_SAPHanaSR/ ) && ( $fWhere =~ /SAPHanaSR.py/ ) ) {
#		#printf("line: %s\n", $_);
#		if ( defined $countId{$fID} ) {
#		   $countId{$fID} = $countId{$fID}+1;
#           if ( $fMessage =~ /SAPHanaSR.srConnectionChanged method called with Dict/ ) {
#              if ( defined $doubles{$fID} ) {
#                  $doubles{$fID} = $doubles{$fID} + 1;
#              } else {
#                  $doubles{$fID} = 1;
#              }
#           }
#		} else {
#		   $countId{$fID} = 1;
#		}
#	}
#}

# sub searchDoubles (ID field)
#while (<>)  {
#    chomp;
#    #    if ( /($idPat)$dnkwti ($date) ($time) ($what) ($where) : ($message)/ ) {
#    #if ( /($idPat)$dnkwti ($date) ($time) ($level) ($what) ($where) : ($message)/) {
#    if ( /($idPat)$dnkwti$WS($date)$WS($time)$WS($level)$WS($what)$WS($where)$WS:$WS($message)/ ) {
#        my ($fID, $fDate, $fTime, $fLevel, $fWhat, $fWhere, $fMessage) = ( $1, $2, $3, $4, $5, $6, $7 );
#        #printf("in: %s\n", $_);
#        #printf("id: %s date: %s time: %s level: %s what: %s where: %s message: %s\n", $1, $2, $3, $4, $5, $6, $7);
#        #if ( $fLevel ne "i" ) {
#        #if ( $fWhat =~ /ha_dr_/ ) {
#        #    printf("line: %s\n", $_);
#        #}
#        if ( ( $fWhat =~ /ha_dr_SAPHanaSR/ ) && ( $fWhere =~ /SAPHanaSR.py/ ) ) {
#            #printf("line: %s\n", $_);
#            if ( defined $countId{$fID} ) {
#               $countId{$fID} = $countId{$fID}+1;
#               if ( $fMessage =~ /\(.*\) SAPHanaSR.srConnectionChanged method called with Dict/ ) {
#                  if ( defined $doubles{$fID} ) {
#                      $doubles{$fID} = $doubles{$fID} + 1;
#                      $times{$fID} = $times{$fID} . " " . $fDate . " " . $fTime;
#                  } else {
#                      $doubles{$fID} = 1;
#                  }
#               }
#            } else {
#               $countId{$fID} = 1;
#            }
#        }
#    }
#}

for my $key ( sort(keys(%countId))) {
    printf("count: %s %s\n", $key, $countId{$key});
}
for my $key ( sort(keys(%doubles))) {
    if ( $doubles{$key} > 1 ) {
        printf("double: %s %s\n", $key, $doubles{$key});
        printf("times: %s %s\n", $key, $times{$key});
    }
}

while (<>)  {
    chomp;
    #    if ( /($idPat)$dnkwti ($date) ($time) ($what) ($where) : ($message)/ ) {
    #if ( /($idPat)$dnkwti ($date) ($time) ($level) ($what) ($where) : ($message)/) {
    if ( /($idPat)$dnkwti$WS($date)$WS($time)$WS($level)$WS($what)$WS($where)$WS:$WS($message)/ ) {
        my ($fID, $fDate, $fTime, $fLevel, $fWhat, $fWhere, $fMessage) = ( $1, $2, $3, $4, $5, $6, $7 );
        #printf("in: %s\n", $_);
        #printf("id: %s date: %s time: %s level: %s what: %s where: %s message: %s\n", $1, $2, $3, $4, $5, $6, $7);
        #if ( $fLevel ne "i" ) {
        #if ( $fWhat =~ /ha_dr_/ ) {
        #    printf("line: %s\n", $_);
        #}
        if ( 
               ( $fWhat =~ /ha_dr_SAPHanaSrM/ ) && ( $fWhere =~ /SAPHanaSrMultiTarget.py/ ) ||
               ( $fWhat =~ /ha_dr_SAPHanaSR/ ) && ( $fWhere =~ /SAPHanaSR.py/ ) 
           ) {
            #printf("line: %s\n", $_);
            if ( defined $countId{$fID} ) {
               $countId{$fID} = $countId{$fID}+1;
            } else {
               $countId{$fID} = 1;
            }
           $runtimes{$fID}->{lastMessage} = $fMessage;
           if ( $fTime =~ /($hour):($minute):($second)\.($msecond)/ ) {
                 $runtimes{$fID}->{Stop} = $1 * 3600 + $2 * 60 + $3;
                 $runtimes{$fID}->{StopTimeString} = $fTime;
                 $runtimes{$fID}->{StopMicroseconds} = $4;
                 #printf("stop %s:%s:%s\n", $1, $2, $3);
           }
           # SAPHanaSrMultiTarget.srConnectionChanged() method called with Dict
           if ( 
                 ( $fMessage =~ /SAPHanaSR.srConnectionChanged.*method called with Dict/ ) ||
                 ( $fMessage =~ /SAPHanaSrMultiTarget.srConnectionChanged.*method called with Dict/ ) 
              ) {
              #
              # start time mark
              #
              if ( $fTime =~ /($hour):($minute):($second)\.($msecond)/ ) {
                 $runtimes{$fID}->{Start} = $1 * 3600 + $2 * 60 + $3;
                 $runtimes{$fID}->{StartTimeStringShort} = $1 . ":" . $2 . ":" . $3;
                 $runtimes{$fID}->{Stop} = -1;
                 $runtimes{$fID}->{StartTimeString} = $fTime;
                 $runtimes{$fID}->{StartDateString} = $fDate;
                 $runtimes{$fID}->{StartMicroseconds} = $4;
                 $runtimes{$fID}->{Hook} = $fWhat;
                 #printf("start %s %s:%s:%s - %s\n", $fID, $1, $2, $3, $runtimes{$fID}->{Start});
              }
              if ( defined $doubles{$fID} ) {
                  $doubles{$fID} = $doubles{$fID} + 1;
                  $times{$fID} = $times{$fID} . " " . $fDate . " " . $fTime;
              } else {
                  $doubles{$fID} = 1;
              }
          }
        }
    }
}

#for my $key ( sort(keys(%countId))) {
#    printf("count: %s %s\n", $key, $countId{$key});
#}
for my $key ( sort(keys(%doubles))) {
    if ( $doubles{$key} > 1 ) {
        #printf("double: %s %s\n", $key, $doubles{$key});
        #printf("times: %s %s\n", $key, $times{$key});
    }
    if ( defined $runtimes{$key}->{Start} && defined $runtimes{$key}->{Stop} ) {
        if ( $runtimes{$key}->{Stop} == -1 ) {
            printf("missing stop time: id: %s start: %s\n", $key, $runtimes{$key}->{Stop} - $runtimes{$key}->{Start});
        } else { 
            my $rt; my $ms;
            $rt = $runtimes{$key}->{Stop} - $runtimes{$key}->{Start};
            $ms = $runtimes{$key}->{StopMicroseconds} - $runtimes{$key}->{StartMicroseconds};
            if ( $rt > 0 && $ms < 0 ) {
               $rt--;
               $ms = $ms + 1000000;
            }
            #debug ausgabe
            #printf("runtime: id: %s rt: %s ms: %s (start: %s, stop: %s)\n", $key, $rt, $ms, $runtimes{$key}->{StartTimeString}, $runtimes{$key}->{StopTimeString});
            #printf("lastMessage: id:%s msg: %s\n", $key, $runtimes{$key}->{lastMessage});

            printf("%s %s %s.%s (%s)\n", $runtimes{$key}->{StartDateString}, $runtimes{$key}->{StartTimeStringShort}, $rt, $ms, $runtimes{$key}->{Hook});
        }
    }
}
